import { Link, useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { useCart } from '../context/CartContext';
import './Cart.css';
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`;
export default function Cart(){
 const {cart,loading,updateItem,removeItem}=useCart(); const navigate=useNavigate(); const [coupon,setCoupon]=useState(''); const [couponState,setCouponState]=useState('');
 const items=cart.items||[]; const subtotal=items.reduce((s,i)=>s+(i.product?.price??i.priceAtAdd)*i.quantity,0); const shipping=subtotal>=999?0:99; const discount=couponState==='applied'?Math.round(subtotal*.1):0; const total=subtotal+shipping-discount;
 if(loading)return <div className="container empty-state">Loading your bag…</div>;
 if(!items.length)return <div className="cart-empty"><span>YOUR BAG</span><h1>Nothing here yet.</h1><p>Good things are waiting. Start exploring the latest TrueGoods collection.</p><Link className="btn btn-dark" to="/products">Shop the collection</Link></div>;
 return <div className="cart-page"><div className="container cart-heading"><div><span>YOUR BAG</span><h1>Shopping bag <small>({items.length})</small></h1></div><Link to="/products">Continue shopping →</Link></div><div className="container cart-layout"><section className="cart-items">{items.map(({product,quantity})=>product&&<article className="cart-item" key={product._id}><Link className="cart-item-image" to={`/products/${product.slug}`}>{product.images?.[0]?<img loading="lazy" decoding="async" src={product.images[0]} alt={product.name}/>:<span>TG</span>}</Link><div className="cart-item-info"><span>{product.category?.name||'TrueGoods collection'}</span><Link to={`/products/${product.slug}`}>{product.name}</Link><small>In stock · Dispatches in 1–2 days</small><button onClick={()=>removeItem(product._id)}>Remove</button></div><div className="cart-item-controls"><div className="cart-qty"><button onClick={()=>quantity===1?removeItem(product._id):updateItem(product._id,quantity-1)}>−</button><span>{quantity}</span><button disabled={quantity>=product.stock} onClick={()=>updateItem(product._id,quantity+1)}>+</button></div><strong>{money(product.price*quantity)}</strong></div></article>)}</section><aside className="cart-summary"><h2>Order summary</h2><div className="summary-line"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div className="summary-line"><span>Delivery</span><strong>{shipping?money(shipping):'Free'}</strong></div>{discount>0&&<div className="summary-line success"><span>TRUE10</span><strong>−{money(discount)}</strong></div>}<div className="cart-progress"><div style={{width:`${Math.min(100,subtotal/999*100)}%`}}/><p>{shipping?'Add '+money(999-subtotal)+' more for free delivery.':'You unlocked free delivery.'}</p></div><div className="coupon-box"><label>Have a promo code?</label><div><input value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="Enter code"/><button onClick={()=>setCouponState(coupon.trim().toUpperCase()==='TRUE10'?'applied':'invalid')}>Apply</button></div>{couponState==='applied'&&<small className="coupon-good">TRUE10 applied — 10% off</small>}{couponState==='invalid'&&<small className="coupon-bad">Try TRUE10 for this demo.</small>}</div><div className="summary-total"><span>Total</span><strong>{money(total)}</strong></div><button className="cart-checkout" onClick={()=>navigate('/checkout')}>Secure checkout <span>→</span></button><p className="cart-safe">🔒 Secure payment powered by Razorpay</p><div className="cart-perks"><span>✓ 7-day returns</span><span>✓ Secure checkout</span><span>✓ Honest pricing</span></div></aside></div></div>
}
