const express = require('express');
const { getProducts, getProductBySlug, createProduct, updateProduct, updateStock, deleteProduct, getAdminProducts, reactivateProduct } = require('../controllers/productController');
const { protect } = require('../middleware/authMiddleware');
const { requireAdmin } = require('../middleware/adminMiddleware');
const router = express.Router();
router.get('/', getProducts);
router.get('/admin/all', protect, requireAdmin, getAdminProducts);
router.post('/', protect, requireAdmin, createProduct);
router.put('/:id', protect, requireAdmin, updateProduct);
router.patch('/:id/stock', protect, requireAdmin, updateStock);
router.patch('/:id/reactivate', protect, requireAdmin, reactivateProduct);
router.delete('/:id', protect, requireAdmin, deleteProduct);
router.get('/:slug', getProductBySlug);
module.exports = router;
